import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const read = (path) => readFileSync(join(root, path), 'utf8');
const failures = [];
let checkCount = 0;

function check(name, condition) {
  checkCount += 1;
  if (!condition) failures.push(name);
}

const models = read('src/lib/models.ts');
const openrouter = read('src/lib/openrouter.ts');
const chatRoute = read('src/app/api/chat/route.ts');
const searchRoute = read('src/app/api/search/route.ts');
const searchLib = read('src/lib/search.ts');
const webExtract = read('src/lib/web-extract.ts');
const researchPlanner = read('src/lib/research-planner.ts');
const titleLib = read('src/lib/title.ts');
const sourceQuality = read('src/lib/source-quality.ts');
const artifactsLib = read('src/lib/artifacts.ts');
const prompts = read('src/lib/prompts.ts');
const db = read('src/lib/db.ts');
const exportLib = read('src/lib/export.ts');
const markdown = read('src/lib/markdown.tsx');
const messageComponent = read('src/components/message.tsx');
const messageActions = read('src/components/message-actions.tsx');
const useSettings = read('src/hooks/use-settings.ts');
const useChat = read('src/hooks/use-chat.ts');
const useConversations = read('src/hooks/use-conversations.ts');
const useDeploymentConfig = read('src/hooks/use-deployment-config.ts');
const appShell = read('src/components/app-shell.tsx');
const sidebar = read('src/components/sidebar.tsx');
const emptyState = read('src/components/empty-state.tsx');
const composer = read('src/components/composer.tsx');
const tasks = read('src/lib/tasks.ts');
const workflowStarters = read('src/lib/workflow-starters.ts');
const researchFallback = read('src/lib/research-fallback.ts');
const researchCitations = read('src/lib/research-citations.ts');
const layout = read('src/app/layout.tsx');
const ogImage = read('src/app/opengraph-image.tsx');
const globals = read('src/app/globals.css');
const packageJson = JSON.parse(read('package.json'));
const envExample = read('.env.example');
const readme = read('README.md');
const deployment = read('DEPLOYMENT.md');
const privacyPage = read('src/app/privacy/page.tsx');
const securityPage = read('src/app/security/page.tsx');
const roadmap = read('ROADMAP.md');
const githubSetup = read('GITHUB_SETUP.md');
const bugTemplate = read('.github/ISSUE_TEMPLATE/bug_report.yml');
const featureTemplate = read('.github/ISSUE_TEMPLATE/feature_request.yml');
const prTemplate = read('.github/pull_request_template.md');

const curatedIds = [...models.matchAll(/id:\s*'([^']+)'/g)].map((match) => match[1]);
const defaultMatch = models.match(/DEFAULT_MODEL_ID\s*=\s*'([^']+)'/);
const fallbackBlock = models.match(/FALLBACK_CHAIN\s*=\s*\[([\s\S]*?)\]/)?.[1] || '';

check('curated model list is present', curatedIds.length > 0);
check('every curated model id is explicitly free', curatedIds.every((id) => id.endsWith(':free')));
check('default model id is explicitly free', Boolean(defaultMatch?.[1].endsWith(':free')));
check('fallback chain does not use router aliases', !/openrouter\/(auto|free)/.test(fallbackBlock));
check('OpenRouter requests enforce zero max price', /max_price:\s*\{[\s\S]*prompt:\s*0[\s\S]*completion:\s*0/.test(openrouter));
check('OpenRouter chat startup has a request timeout', /OPENROUTER_REQUEST_TIMEOUT_MS/.test(openrouter) && /fetchOpenRouterWithTimeout/.test(openrouter));
check('dynamic model fetch requires :free ids', /id\.endsWith\(':free'\)/.test(openrouter));
check('chat route rejects non-free model ids', /isFreeModelId\(model\)/.test(chatRoute));
check('hosted quota commits after provider acceptance', /commitHostedQuota\(hostedQuota\)/.test(chatRoute) && /getHostedQuotaStatus/.test(chatRoute));
check('hosted quota response omits internal identity', /publicHostedUsage/.test(chatRoute) && /Omit<HostedQuota, 'identity'>/.test(chatRoute));
check('hosted search quota commits after search success', /commitHostedSearchQuota\(hostedQuota\)/.test(searchRoute) && /getHostedSearchQuotaStatus/.test(searchRoute));
check('hosted search quota has response headers', /X-OpenConvo-Search-Limit/.test(searchRoute) && /X-OpenConvo-Search-Remaining/.test(searchRoute));
check('search route exposes provider metadata', /X-OpenConvo-Search-Provider/.test(searchRoute));
check('search route has bounded serverless budget', /export const maxDuration = 60/.test(searchRoute) && /SEARCH_ROUTE_BUDGET_MS/.test(searchRoute) && /RESEARCH_PLANNER_BUDGET_MS/.test(searchRoute));
check('web search has provider fallback', /SearchProvider/.test(searchLib) && /tavilyProvider/.test(searchLib) && /duckDuckGoProvider/.test(searchLib));
check('keyless search has secondary HTML fallbacks', /DUCKDUCKGO_LITE/.test(searchLib) && /duckDuckGoLiteProvider/.test(searchLib) && /BING_SEARCH/.test(searchLib) && /bingHtmlProvider/.test(searchLib) && /parseDuckDuckGoHtml/.test(searchLib));
check('research search aggregates multiple providers', /providerResults/.test(searchLib) && /mode === 'search'/.test(searchLib) && /providers/.test(searchLib));
check('social trend research seeds public snapshot sources', /seededReferenceResults/.test(searchLib) && /trends24\.in/.test(searchLib) && /twitter-trends\.snaplytics/.test(searchLib));
check('research source diversification enforces host caps', /MIN_DIVERSIFIED_RESULTS/.test(searchLib) && /selected\.size >= MIN_DIVERSIFIED_RESULTS/.test(searchLib) && !/for \(const result of comparisonResults\) \{\s*selected\.set\(canonicalUrlKey\(result\.url\), result\);\s*\}/.test(searchLib));
check('web search supports optional SearxNG', /searxngProvider/.test(searchLib) && /SEARXNG_URL/.test(searchLib));
check('web search providers have timeouts and cache', /SEARCH_TIMEOUT_MS/.test(searchLib) && /withTimeout/.test(searchLib) && /searchCache/.test(searchLib));
check('web search enriches results with page extraction', /enrichSearchResults/.test(searchRoute) && /fetchReadablePage/.test(webExtract));
check('web extraction blocks local network fetches', /isBlockedHostname/.test(webExtract) && /169/.test(webExtract) && /192/.test(webExtract));
check('web extraction caches fetched pages', /pageCache/.test(webExtract) && /PAGE_CACHE_TTL_MS/.test(webExtract));
check('search and extraction strip tracking params', /TRACKING_QUERY_PARAMS/.test(searchLib) && /TRACKING_QUERY_PARAMS/.test(webExtract) && /fbclid/.test(searchLib) && /msclkid/.test(webExtract));
check('search dedupes repeated titles from the same host', /seenTitleHosts/.test(searchLib) && /normalizeDedupeTitle/.test(searchLib));
check('research mode plans multiple queries', /planResearchQueries/.test(searchRoute) && /searchWebMany/.test(searchLib) && /MAX_PLANNED_QUERIES\s*=\s*8/.test(researchPlanner));
check('research mode uses model planner before heuristic fallback', /generateResearchPlan/.test(searchRoute) && /planner:\s*'model'/.test(searchRoute) && /planner:\s*'heuristic'/.test(searchRoute));
check('auto mode has broad web research triggers', /needsWebResearch/.test(tasks) && /latest\|current/.test(tasks) && /looksLikeExternalDecision/.test(tasks));
check('auto mode routes social trends to research', /trending\|trends\|viral/.test(tasks) && /twitter\|x\\\.com\|reddit/.test(tasks));
check('auto mode routes budget and spec lists to research', /budget\|under\|below\|within/.test(tasks) && /cc\|bhp\|nm\|kmpl/.test(tasks) && /give me the list/.test(tasks));
check('research planner uses generic query analysis', /analyzeResearchQuery/.test(researchPlanner) && /inferResearchIntent/.test(researchPlanner) && /extractCandidateSubjects/.test(researchPlanner));
check('research planner avoids topic-specific subject hardcoding', !/OpenAI|ChatGPT|Claude|Anthropic|Continental|GT 650|Supabase|Firebase/.test(researchPlanner));
check('research planner decomposes by intent and subject', /subjectQueries/.test(researchPlanner) && /intentQueries/.test(researchPlanner) && /STOP_WORDS/.test(researchPlanner));
check('research planner handles comparisons without topic dictionaries', /extractComparisonSubjects/.test(researchPlanner) && /stripAudienceContext/.test(researchPlanner));
check('research planner strips generic question frames', /stripQuestionFrame/.test(researchPlanner) && /which\|what/.test(researchPlanner) && /should\|can\|could/.test(researchPlanner));
check('research planner handles purchase constraints generically', /buildConstraintSearchQuery/.test(researchPlanner) && /extractPurchaseSubjects/.test(researchPlanner) && /extractBudgetConstraint/.test(researchPlanner));
check('research planner derives market scope from currency', /extractMarketScope/.test(researchPlanner) && /inr/.test(researchPlanner) && /India/.test(researchPlanner));
check('research planner handles live events generically', /liveEvent/.test(researchPlanner) && /extractNamedSubjects/.test(researchPlanner) && /official schedule fixtures results/.test(researchPlanner));
check('research planner handles social trends generically', /socialTrend/.test(researchPlanner) && /trend tracker snapshot/.test(researchPlanner) && /trending hashtags topics/.test(researchPlanner));
check('deep research mode expands query and source depth', /deep-research/.test(searchRoute) && /MAX_DEEP_PLANNED_QUERIES/.test(researchPlanner) && /maxCombinedResultsForMode/.test(searchLib));
check('research trace is saved on messages', /researchTrace/.test(useChat) && /buildResearchTrace/.test(useChat));
check('research trace renders in source panel', /Research trace/.test(messageComponent) && /plannedQueries/.test(messageComponent));
check('research progress is visible before synthesis', /researchStatus/.test(useChat) && /ResearchProgress/.test(read('src/components/chat-area.tsx')));
check('search results are quality ranked', /rankSearchResults/.test(searchLib) && /sourceScore/.test(sourceQuality));
check('source quality favors primary evidence across topics', /needsPrimaryEvidence/.test(sourceQuality) && /not a primary source/.test(sourceQuality));
check('source quality understands live event evidence', /needsLiveEventEvidence/.test(sourceQuality) && /event data terms/.test(sourceQuality));
check('source quality understands social trend evidence', /needsTrendEvidence/.test(sourceQuality) && /trend snapshot terms/.test(sourceQuality) && /TREND_SNAPSHOT_HOST_HINTS/.test(sourceQuality));
check('source quality downranks generic social landing pages', /generic social landing page/.test(sourceQuality) && /explore\|home\|login/.test(sourceQuality));
check('comparison search keeps evidence diverse across entities and hosts', /diversifyResearchResults/.test(searchLib) && /diversifyByEntities/.test(searchLib) && /hostKey/.test(searchLib));
check('provider errors are deduplicated across planned queries', /new Set\(responses\.flatMap/.test(searchLib));
check('comparison search has no topic-specific vendor branch', !/needsOpenAI|needsAnthropic|sourceFamily|addRepresentativeResult/.test(searchLib));
check('source quality is exposed to prompts and UI', /Quality:/.test(prompts) && /sourceLabel/.test(messageComponent));
check('chat route preserves source quality for prompting', /sourceScore/.test(chatRoute) && /sourceReason/.test(chatRoute));
check('research prompts include current date and stale-memory guardrails', /Current Date/.test(prompts) && /supplied sources/.test(prompts) && /available details/.test(prompts));
check('research prompts forbid knowledge-cutoff phrasing', /based on my current knowledge/.test(prompts) && /knowledge cutoff/.test(prompts) && /must be grounded/.test(prompts));
check('research prompt asks for verdict-first compact answers', /Start with a short direct answer or verdict/.test(prompts) && /small comparison table/.test(prompts));
check('research prompts support social trend snapshots', /public trend trackers/.test(prompts) && /direct Twitter, Reddit, or platform API access/.test(prompts));
check('research failures fall back to source-backed answers', /buildResearchFallbackAnswer/.test(researchFallback) && /buildClientResearchFallback/.test(useChat) && /emittedContent/.test(chatRoute));
check('research answers enforce visible source citations', /ensureResearchCitations/.test(researchCitations) && /buildSourcesSection/.test(researchCitations) && /hasRealSourceLinks/.test(researchCitations) && /citations/.test(chatRoute));
check('research source pills are visible above source panel', /SourcePills/.test(messageComponent) && /\[\{index \+ 1\}\]/.test(messageComponent));
check('research loading state explains source drafting', /Drafting from sources/.test(messageComponent) && /Sources will be attached/.test(messageComponent));
check('message actions stay clickable while hovering', !/opacity-0 group-hover:opacity-100/.test(messageActions) && !/md:opacity-0/.test(messageComponent) && /relative z-10 mt-2 opacity-100/.test(messageComponent));
check('markdown tables remain contained', /overflow-x: auto/.test(globals) && /vertical-align: top/.test(globals));
check('chat stream stalls are bounded and recoverable', /CHAT_STREAM_IDLE_TIMEOUT_MS/.test(chatRoute) && /readStreamChunkWithTimeout/.test(chatRoute) && /did not stream a response in time/.test(chatRoute));
check('client search and title requests have timeouts', /SEARCH_REQUEST_TIMEOUT_MS/.test(useChat) && /TITLE_REQUEST_TIMEOUT_MS/.test(useChat) && /fetchWithTimeout/.test(useChat));
check('research retries progressively shrink context', /RESEARCH_RETRY_SOURCE_LIMITS/.test(useChat) && /compactSearchResultsForAttempt/.test(useChat) && /MAX_SOURCE_CONTENT_CHARS/.test(prompts) && /MAX_SEARCH_CONTENT_CHARS/.test(chatRoute));
check('local conversation titles are summarized, not raw first prompts', /buildConversationTitle/.test(titleLib) && /buildComparisonTitle/.test(titleLib) && /buildPurchaseTitle/.test(titleLib) && /buildFeatureTitle/.test(titleLib) && /buildConversationTitle/.test(useChat) && /buildConversationTitle/.test(openrouter) && !/function buildLocalTitle/.test(useChat));
check('research reports are extracted as artifacts', /extractResearchReportArtifact/.test(artifactsLib) && /Research Evidence/.test(artifactsLib));
check('artifacts can be exported directly', /handleDownload/.test(read('src/components/artifact-panel.tsx')) && /artifactExtension/.test(read('src/components/artifact-panel.tsx')));
check('database migration repairs artifact indexes', /artifactStore\.indexNames\.contains\('by-project'\)/.test(db));
check('imports repair unsafe model ids', /resolveSafeModelId/.test(exportLib));
check('imports cap large text fields', /MAX_MESSAGE_CHARS/.test(exportLib) && /MAX_ARTIFACT_CHARS/.test(exportLib));
check('imports reject oversized files before reading', /MAX_IMPORT_BYTES/.test(exportLib) && /file\.size > MAX_IMPORT_BYTES/.test(exportLib));
check('markdown links are sanitized', /safeExternalUrl/.test(markdown));
check('search result links are sanitized', /safeExternalUrl/.test(messageComponent));
check('settings loaded from localStorage are normalized', /normalizeSettings/.test(useSettings) && /normalizePromptSnippets/.test(useSettings));
check('app shell uses dynamic viewport height', /h-dvh/.test(appShell));
check('app logos link to homepage', /href="\/"/.test(sidebar) && /href="\/"/.test(appShell) && /href="\/"/.test(emptyState));
check('site metadata includes social previews', /openGraph/.test(layout) && /twitter/.test(layout) && /metadataBase/.test(layout));
check('Open Graph image route exists', /ImageResponse/.test(ogImage) && /1200/.test(ogImage) && /630/.test(ogImage));
check('mobile sidebar has wide overlay', /92vw/.test(sidebar));
check('empty state has mobile and short viewport rules', /empty-features/.test(globals) && /max-height: 760px/.test(globals) && /max-width: 640px/.test(globals));
check('chat streaming uses display smoothing', /createStreamingDisplay/.test(useChat) && /takeStreamingChunk/.test(useChat));
check('streaming does not force-scroll after user scrolls up', /shouldStickToBottomRef/.test(read('src/components/chat-area.tsx')) && /isStreaming && shouldStickToBottomRef\.current/.test(read('src/components/chat-area.tsx')));
check('empty chat streams retry automatically', /EMPTY_RESPONSE_RETRY_ATTEMPTS/.test(useChat) && /after automatic retries/.test(useChat));
check('active conversation survives refresh', /openconvo\.activeConversationId/.test(useConversations) && /getStoredConversationId/.test(useConversations) && /if \(loading\) return/.test(useConversations));
check('deployment config gates first render', /loaded:\s*false/.test(useDeploymentConfig) && /deploymentConfig\.loaded/.test(appShell));
check('workflow starters are rendered on empty state', /WORKFLOW_STARTERS/.test(emptyState) && /onStartWorkflow/.test(emptyState));
check('workflow starters create editable composer drafts', /workflowDraft/.test(composer) && /setContent\(workflowDraft\.starter\.prompt\)/.test(composer));
check('workflow starter prompts cover core task modes', /research-brief/.test(workflowStarters) && /file-analysis/.test(workflowStarters) && /code-review/.test(workflowStarters) && /compare-models/.test(workflowStarters));
check('test script is wired', packageJson.scripts?.test === 'node scripts/launch-checks.mjs');
check('dev script matches webpack config', !/--turbopack/.test(packageJson.scripts?.dev || '') || !/webpack\s*:/.test(read('next.config.ts')));
check('.env.example documents OpenRouter', /OPENROUTER_API_KEY/.test(envExample));
check('.env.example documents Tavily', /TAVILY_API_KEY/.test(envExample));
check('.env.example documents SearxNG', /SEARXNG_URL/.test(envExample));
check('.env.example documents hosted free limit', /OPENCONVO_HOSTED_FREE_DAILY_LIMIT/.test(envExample));
check('.env.example documents hosted search limit', /OPENCONVO_HOSTED_SEARCH_DAILY_LIMIT/.test(envExample));
check('.env.example documents GitHub URL', /NEXT_PUBLIC_GITHUB_URL/.test(envExample));
check('.env.example documents site URL', /NEXT_PUBLIC_SITE_URL/.test(envExample));
check('README has setup instructions', /npm install/.test(readme) && /npm run dev/.test(readme));
check('README has deploy button', /Deploy with Vercel/.test(readme));
check('README links deployment guide', /DEPLOYMENT\.md/.test(readme));
check('README links roadmap and contributing guide', /ROADMAP\.md/.test(readme) && /CONTRIBUTING\.md/.test(readme));
check('deployment guide documents Vercel', /Vercel/.test(deployment) && /OPENROUTER_API_KEY/.test(deployment));
check('privacy page documents local storage', /browser/.test(privacyPage) && /API keys/.test(privacyPage));
check('security page documents hosted limits', /Hosted limits/.test(securityPage) && /rate limiting/.test(securityPage));
check('roadmap documents non-goals', /Non-Goals/.test(roadmap));
check('GitHub setup documents repo topics', /Topics/.test(githubSetup) && /openrouter/.test(githubSetup));
check('GitHub issue templates exist', /Bug report/.test(bugTemplate) && /Feature request/.test(featureTemplate));
check('pull request template requires safety checks', /Free-model routing/.test(prTemplate) && /npm run build/.test(prTemplate));
check('license file exists', existsSync(join(root, 'LICENSE')));

if (failures.length > 0) {
  console.error('Launch checks failed:');
  for (const failure of failures) console.error(`- ${failure}`);
  process.exit(1);
}

console.log(`Launch checks passed (${checkCount} checks).`);
